var groupedInsOptions = {
  insurer_name_options: [
    { value: 'a_g_zurich', text: 'A G Zurich' },
    { value: 'a.c.c._bank', text: 'A.C.C. Bank' },
    { value: 'a.c.c._mortgages', text: 'A.C.C. Mortgages' },
    { value: 'aa_mutual_international', text: 'AA Mutual International' },
    { value: 'abacus', text: 'ABACUS' },
    { value: 'abbey_life_assurance', text: 'Abbey Life Assurance' },
    { value: 'abbey_life_executive_mortgages_ltd', text: 'Abbey Life Executive Mortgages Ltd' },
    { value: 'abbey_life_funding_ltd', text: 'Abbey Life Funding Ltd' },
    { value: 'abbey_life_home_loans_ltd', text: 'Abbey Life Home Loans Ltd' },
    { value: 'abbey_motor_policies', text: 'Abbey Motor Policies' },
    { value: 'abbey_national_plc', text: 'Abbey National Plc' },
    { value: 'abc_insurance', text: 'ABC Insurance' },
    { value: 'abc_international_bank_plc', text: 'ABC International Bank PLC' },
    { value: 'abn_amro_bank', text: 'ABN Amro Bank' },
    { value: 'acc_building_society', text: 'ACC Building Society' },
    { value: 'accord_mortgage_company', text: 'Accord Mortgage Company' },
    { value: 'accord_mortgages', text: 'Accord Mortgages' },
    { value: 'acenden_mortgage_service_specialists', text: 'Acenden Mortgage Service Specialists' },
    { value: 'acme_motor_policies', text: 'Acme Motor Policies' },
    { value: 'acromas_insurance_company_ltd_(aicl)', text: 'Acromas Insurance Company Ltd (AICL)' },
    { value: 'admiral_insurance', text: 'Admiral Insurance' },
    { value: 'advantage_innovative_lending', text: 'Advantage Innovative Lending' },
    { value: 'affinitas_ltd', text: 'Affinitas Ltd' },
    { value: 'affirmative_finance_limited', text: 'Affirmative Finance Limited' },
    { value: 'ageas_insurance_ltd', text: 'Ageas Insurance Ltd' },
    { value: 'agf_insurance_limited', text: 'AGF Insurance Limited' },
    { value: 'agricultural_&amp;_general_insurance', text: 'Agricultural &amp; General Insurance' },
    { value: 'agricultural_credit_association', text: 'Agricultural Credit Association' },
    { value: 'ahli_united_bank_(uk)_plc', text: 'Ahli United Bank (UK) plc' },
    { value: 'aib_bank', text: 'AIB Bank' },
    { value: 'aib_business_bank', text: 'AIB Business Bank' },
    { value: 'aib_financa_&amp;_leasing', text: 'AIB Financa &amp; Leasing' },
    { value: 'aib_group_(uk)_plc', text: 'AIB Group (UK) plc' },
    { value: 'aib_home_mortgages', text: 'AIB Home Mortgages' },
    { value: 'aig_insurance_ireland', text: 'AIG Insurance Ireland' },
    { value: 'aioi_insurance', text: 'Aioi Insurance' },
    { value: 'airdrie_savings_bank', text: 'Airdrie Savings Bank' },
    { value: 'albany_life_assurance_co_ltd', text: 'Albany Life Assurance Co Ltd' },
    { value: 'albion_insurance_co_ltd', text: 'Albion Insurance Co Ltd' },
    { value: 'aldermore_bank', text: 'Aldermore Bank' },
    { value: 'algemene_bank_nederland', text: 'Algemene Bank Nederland' },
    { value: 'allchurches_mortgage_company_ltd', text: 'Allchurches Mortgage Company Ltd' },
    { value: 'alliance_&amp;_leicester_plc', text: 'Alliance &amp; Leicester plc' },
    { value: 'allianz_insurance_plc', text: 'Allianz Insurance PLC' },
    { value: 'allianz_n.i.', text: 'Allianz N.I.' },
    { value: 'allied_dunbar', text: 'Allied Dunbar' },
    { value: 'allied_irish_bank_(gb)', text: 'Allied Irish Bank (GB)' },
    { value: 'allied_irish_finance_co_ltd', text: 'Allied Irish Finance Co Ltd' },
    { value: 'allied_irish_mortgages', text: 'Allied Irish Mortgages' },
    { value: 'als', text: 'ALS' },
    { value: 'ambassador_policies', text: 'Ambassador Policies' },
    { value: 'amber_homeloans', text: 'Amber Homeloans' },
    { value: 'american_express_international_banking_corporation', text: 'American Express International Banking Corporation' },
    { value: 'american_international_underwriters_(uk)_limited', text: 'American International Underwriters (UK) Limited' },
    { value: 'amev_insurance_ireland', text: 'Amev Insurance Ireland' },
    { value: 'amicus_finance_plc', text: 'Amicus Finance plc' },
    { value: 'amlin_uk', text: 'Amlin UK' },
    { value: 'amtrust_europe_limited', text: 'AmTrust Europe Limited' },
    { value: 'anchor_underwriters', text: 'Anchor Underwriters' },
    { value: 'ancient_order_of_foresters_friendly_society', text: 'Ancient Order Of Foresters Friendly Society' },
    { value: 'anglo_irish_assurance', text: 'Anglo Irish Assurance' },
    { value: 'anglo_irish_bank', text: 'Anglo Irish Bank' },
    { value: 'ansvar_insurance', text: 'Ansvar Insurance' },
    { value: 'aqmen_ltd', text: 'aQmen Ltd' },
    { value: 'arb_underwriting_ltd', text: 'ARB Underwriting Ltd' },
    { value: 'ark_life', text: 'Ark Life' },
    { value: 'aron_insurance', text: 'Aron Insurance' },
    { value: 'associates_capital_corporation_ltd', text: 'Associates Capital Corporation Ltd' },
    { value: 'athlone_county_council', text: 'Athlone County Council' },
    { value: 'athlone_urban_district_council', text: 'Athlone Urban District Council' },
    { value: 'athy_urban_district_council', text: 'Athy Urban District Council' },
    { value: 'atlas_assurance', text: 'Atlas Assurance' },
    { value: 'automobile_association_insurance_co_ltd', text: 'Automobile Association Insurance Co Ltd' },
    { value: 'avco_trust_ltd', text: 'Avco Trust Ltd' },
    { value: 'aviva', text: 'Aviva' },
    { value: 'aviva,_ireland', text: 'Aviva, Ireland' },
    { value: 'avon_insurance', text: 'Avon Insurance' },
    { value: 'axa_broker,_ireland', text: 'AXA Broker, Ireland' },
    { value: 'axa_insurance_company_limited', text: 'AXA Insurance Company Limited' },
    { value: 'axa_insurance_uk_plc', text: 'AXA Insurance UK PLC' },
    { value: 'axa_insurance,_ireland', text: 'AXA Insurance, Ireland' },
    { value: 'b.n.p._mortgages_ltd', text: 'B.N.P. Mortgages Ltd' },
    { value: 'ballina_urban_district_council', text: 'Ballina Urban District Council' },
    { value: 'banc_aontas_eireann', text: 'Banc Aontas Eireann' },
    { value: 'bank_america_finance_co_ltd', text: 'Bank America Finance Co Ltd' },
    { value: 'bank_leumi_(uk)_plc', text: 'Bank Leumi (UK) Plc' },
    { value: 'bank_national_du_paris', text: 'Bank National Du Paris' },
    { value: 'bank_of_america_nt_&amp;_sa', text: 'Bank Of America NT &amp; SA' },
    { value: 'bank_of_china_(uk)_ltd', text: 'Bank of China (UK) Ltd' },
    { value: 'bank_of_credit_&amp;_commerce_international', text: 'Bank Of Credit &amp; Commerce International' },
    { value: 'bank_of_cyprus_(london)_ltd', text: 'Bank of Cyprus (London) Ltd' },
    { value: 'bank_of_east_asia_ltd', text: 'Bank of East Asia Ltd' },
    { value: 'bank_of_india_ltd', text: 'Bank Of India Ltd' },
    { value: 'bank_of_ireland', text: 'Bank Of Ireland' },
    { value: 'bank_of_ireland_business_bank', text: 'Bank Of Ireland Business Bank' },
    { value: 'bank_of_ireland_finance', text: 'Bank Of Ireland Finance' },
    { value: 'bank_of_ireland_home_mortgages_ltd', text: 'Bank Of Ireland Home Mortgages Ltd' },
    { value: 'bank_of_ireland_mortgages', text: 'Bank of Ireland Mortgages' },
    { value: 'bank_of_montreal', text: 'Bank Of Montreal' },
    { value: 'bank_of_scotland', text: 'Bank Of Scotland' },
    { value: 'bank_of_scotland_ireland', text: 'Bank of Scotland Ireland' },
    { value: 'banque_nationale_de_paris_ltd', text: 'Banque Nationale De Paris Ltd' },
    { value: 'baptist_insurance_company_limited', text: 'Baptist Insurance Company Limited' },
    { value: 'barbican_insurance_group', text: 'Barbican Insurance Group' },
    { value: 'barclays_bank_plc', text: 'Barclays Bank Plc' },
    { value: 'barclays_direct_mortgage_service', text: 'Barclays Direct Mortgage Service' },
    { value: 'barnsley_building_society', text: 'Barnsley Building Society' },
    { value: 'basinghall_finance_plc', text: 'Basinghall Finance PLC' },
    { value: 'bath_investment_&amp;_building_society', text: 'Bath Investment &amp; Building Society' },
    { value: 'beacon', text: 'Beacon' },
    { value: 'beacon_homes_ltd', text: 'Beacon Homes Ltd' },
    { value: 'bear_stearns_home_loans', text: 'Bear Stearns Home Loans' },
    { value: 'beaufort_insurance_company_limited', text: 'Beaufort Insurance Company Limited' },
    { value: 'beazley_underwriting_services_limited', text: 'Beazley Underwriting Services Limited' },
    { value: 'bedford_building_society', text: 'Bedford Building Society' },
    { value: 'bell_insurance', text: 'Bell Insurance' },
    { value: 'beneficial_bank_plc', text: 'Beneficial Bank plc' },
    { value: 'beverley_building_society', text: 'Beverley Building Society' },
    { value: 'birmingham_midshires_building_society', text: 'Birmingham Midshires Building Society' },
    { value: 'birmingham_midshires_mortgage_services_ltd', text: 'Birmingham Midshires Mortgage Services Ltd' },
    { value: 'bishopsgate_insurance_limited', text: 'Bishopsgate Insurance Limited' },
    { value: 'black_horse_life_assurance_co_ltd', text: 'Black Horse Life Assurance Co Ltd' },
    { value: 'black_sea_&amp;_baltic_general_insurance_limited', text: 'Black Sea &amp; Baltic General Insurance Limited' },
    { value: 'blackfriars_insurance_company_limited', text: 'Blackfriars Insurance Company Limited' },
    { value: 'blemain_finance', text: 'Blemain Finance' },
    { value: 'bluesure', text: 'Bluesure' },
    { value: 'bnp_paribas', text: 'BNP Paribas' },
    { value: 'boston_safe_deposit_&amp;_trust_co', text: 'Boston Safe Deposit &amp; Trust Co' },
    { value: 'boston_trust_/_savings_ltd', text: 'Boston Trust / Savings Ltd' },
    { value: 'bradford_&amp;_bingley_building_society', text: 'Bradford &amp; Bingley Building Society' },
    { value: 'bradford_pennine_insurance_company_limited', text: 'Bradford Pennine Insurance Company Limited' },
    { value: 'bray_county_council', text: 'Bray County Council' },
    { value: 'bray_urban_district_council', text: 'Bray Urban District Council' },
    { value: 'bristol_&amp;_west_investments_plc', text: 'Bristol &amp; West Investments PLC' },
    { value: 'bristol_&amp;_west_plc', text: 'Bristol &amp; West plc' },
    { value: 'brit_insurance', text: 'Brit Insurance' },
    { value: 'britannia_building_society', text: 'Britannia Building Society' },
    { value: 'britannic', text: 'Britannic' },
    { value: 'britannic_assurance_co_plc', text: 'Britannic Assurance Co Plc' },
    { value: 'britannic_money', text: 'Britannic Money' },
    { value: 'british_coal', text: 'British Coal' },
    { value: 'british_commonwealth_insurance', text: 'British Commonwealth Insurance' },
    { value: 'british_equitable_assurance', text: 'British Equitable Assurance' },
    { value: 'british_linen_bank', text: 'British Linen Bank' },
    { value: 'british_standard_assurance_association', text: 'British Standard Assurance Association' },
    { value: 'brittanic_assurance_plc', text: 'Brittanic Assurance Plc' },
    { value: 'broker_direct', text: 'Broker Direct' },
    { value: 'broker_line_direct,_dublin', text: 'Broker Line Direct, Dublin' },
    { value: 'buckinghamshire_building_society', text: 'Buckinghamshire Building Society' },
    { value: 'budget_insurance_company_limited', text: 'Budget Insurance Company Limited' },
    { value: 'builders_accident_insurance', text: 'Builders Accident Insurance' },
    { value: 'bundoran_urban_district_council', text: 'Bundoran Urban District Council' },
    { value: 'c_&amp;_g_guardian', text: 'C &amp; G Guardian' },
    { value: 'c_l_mortgages_limited', text: 'C L Mortgages Limited' },
    { value: 'c.i.b.c._mortgages_plc', text: 'C.I.B.C. Mortgages Plc' },
    { value: 'caledonian_insurance', text: 'Caledonian Insurance' },
    { value: 'cambridge_building_society', text: 'Cambridge Building Society' },
    { value: 'canada_life', text: 'Canada Life' },
    { value: 'canada_permanent_building_society', text: 'Canada Permanent Building Society' },
    { value: 'canada_permanent_mortgage_corporation_(uk)_ltd', text: 'Canada Permanent Mortgage Corporation (UK) Ltd' },
    { value: 'canopius_managing_agents_limited', text: 'Canopius Managing Agents Limited' },
    { value: 'capital_bank_mortgages_ltd', text: 'Capital Bank Mortgages Ltd' },
    { value: 'capital_bridging_finance', text: 'Capital Bridging Finance' },
    { value: 'capital_home_loans_ltd', text: 'Capital Home Loans Ltd' },
    { value: 'car_and_general_insurance', text: 'Car and General Insurance' },
    { value: 'carlow_county_council', text: 'Carlow County Council' },
    { value: 'carlow_urban_district_council', text: 'Carlow Urban District Council' },
    { value: 'carrick-on-shannon_urban_district_council', text: 'Carrick-On-Shannon Urban District Council' },
    { value: 'carrick-on-suir_urban_district_council', text: 'Carrick-On-Suir Urban District Council' },
    { value: 'carrickmacross_urban_district_council', text: 'Carrickmacross Urban District Council' },
    { value: 'castlebar_urban_district_council', text: 'Castlebar Urban District Council' },
    { value: 'casualty_and_general_insurance_company_(europe)_limited', text: 'Casualty and General Insurance Company (Europe) Limited' },
    { value: 'catalyst_securitas_limited', text: 'Catalyst Securitas Limited' },
    { value: 'catholic_building_society', text: 'Catholic Building Society' },
    { value: 'cavan_county_council', text: 'Cavan County Council' },
    { value: 'cavan_credit_union', text: 'Cavan Credit Union' },
    { value: 'cavan_urban_district_council', text: 'Cavan Urban District Council' },
    { value: 'cedar_holding_ltd', text: 'Cedar Holding Ltd' },
    { value: 'celtic_international_insurance,_galway', text: 'Celtic International Insurance, Galway' },
    { value: 'central_bank_of_ireland', text: 'Central Bank Of Ireland' },
    { value: 'central_homeloans_ltd', text: 'Central Homeloans Ltd' },
    { value: 'cgu_insurance', text: 'CGU Insurance' },
    { value: 'cgu_life', text: 'CGU Life' },
    { value: 'chancellors_masters_&amp;_scholars_of_university_of_cambridge', text: 'Chancellors Masters &amp; Scholars Of University Of Cambridge' },
    { value: 'charter_mortgages', text: 'Charter Mortgages' },
    { value: 'charterhouse_japhet_credit_ltd', text: 'Charterhouse Japhet Credit Ltd' },
    { value: 'charterhouse_japhet_plc', text: 'Charterhouse Japhet Plc' },
    { value: 'chartis_europe_limited', text: 'Chartis Europe Limited' },
    { value: 'chartis_insurance_ireland', text: 'Chartis Insurance Ireland' },
    { value: 'chaucer_insurance', text: 'Chaucer Insurance' },
    { value: 'chelsea_building_society', text: 'Chelsea Building Society' },
    { value: 'chelsea_mortgage_services', text: 'Chelsea Mortgage Services' },
    { value: 'cheltenham_&amp;_gloucester_plc', text: 'Cheltenham &amp; Gloucester plc' },
    { value: 'chemical_bank_home_loans_ltd', text: 'Chemical Bank Home Loans Ltd' },
    { value: 'chesham_building_society', text: 'Chesham Building Society' },
    { value: 'cheshire_building_society', text: 'Cheshire Building Society' },
    { value: 'cheshire_mortgage_corporation', text: 'Cheshire Mortgage Corporation' },
    { value: 'cheval_property_finance_plc', text: 'Cheval Property Finance PLC' },
    { value: 'china_insurance_company_(uk)_limited', text: 'China Insurance Company (UK) Limited' },
    { value: 'chl_mortgages', text: 'CHL Mortgages' },
    { value: 'chorley_&amp;_district_building_society', text: 'Chorley &amp; District Building Society' },
    { value: 'chubb_insurance', text: 'Chubb Insurance' },
    { value: 'chubb_insurance,_dublin', text: 'Chubb Insurance, Dublin' },
    { value: 'chubb_inurance_company_of_europe_sa', text: 'Chubb Inurance Company of Europe SA' },
    { value: 'church_&amp;_general_insurance,_ireland', text: 'Church &amp; General Insurance, Ireland' },
    { value: 'church_and_general_insurance_company_limited', text: 'Church And General Insurance Company Limited' },
    { value: 'church_home_trust_plc', text: 'Church Home Trust PLC' },
    { value: 'churchill_insurance_company_limited', text: 'Churchill Insurance Company Limited' },
    { value: 'chyoda_fire_&amp;_marine_insurance_company_(europe)_limited', text: 'Chyoda Fire &amp; Marine Insurance Company (Europe) Limited' },
    { value: 'cia', text: 'CIA' },
    { value: 'cigna_insurance_of_europe', text: 'Cigna Insurance of Europe' },
    { value: 'cin_properties', text: 'Cin Properties' },
    { value: 'citibank_assurance_co_ltd', text: 'Citibank Assurance Co Ltd' },
    { value: 'citibank_international_plc', text: 'Citibank International plc' },
    { value: 'citibank_mortgage', text: 'Citibank Mortgage' },
    { value: 'citibank_na', text: 'Citibank NA' },
    { value: 'citibank_savings', text: 'Citibank Savings' },
    { value: 'citibank_trust_ltd', text: 'Citibank Trust Ltd' },
    { value: 'citifinancial', text: 'Citifinancial' },
    { value: 'city_&amp;_provincial_home_loans_ltd', text: 'City &amp; Provincial Home Loans Ltd' },
    { value: 'city_bank_plc', text: 'City Bank Plc' },
    { value: 'city_of_westminster', text: 'City of Westminster' },
    { value: 'clare_county_council', text: 'Clare County Council' },
    { value: 'clay_cross_building_society', text: 'Clay Cross Building Society' },
    { value: 'clonmel_corporation', text: 'Clonmel Corporation' },
    { value: 'close_mortgages', text: 'Close Mortgages' },
    { value: 'cloverleaf', text: 'Cloverleaf' },
    { value: 'clydesdale_bank_plc', text: 'Clydesdale Bank Plc' },
    { value: 'cna_international', text: 'CNA International' },
    { value: 'co-operative_bank_plc', text: 'Co-operative Bank Plc' },
    { value: 'co-operative_insurance_society_limited', text: 'Co-operative Insurance Society Limited' },
    { value: 'colonial_insurance_company', text: 'Colonial Insurance Company' },
    { value: 'colonial_mutual_life_assurance_society', text: 'Colonial Mutual Life Assurance Society' },
    { value: 'comhair_iorrais', text: 'Comhair Iorrais' },
    { value: 'comhar_creidmheasa', text: 'Comhar Creidmheasa' },
    { value: 'comhar_i.n.t.o.', text: 'Comhar I.N.T.O.' },
    { value: 'comhlucht_na_heiran', text: 'Comhlucht Na Heiran' },
    { value: 'commercial_acceptances_ltd', text: 'Commercial Acceptances Ltd' },
    { value: 'commercial_credit_finance_co_ltd', text: 'Commercial Credit Finance Co Ltd' },
    { value: 'commercial_credit_home_loans_corporation_ltd', text: 'Commercial Credit Home Loans Corporation Ltd' },
    { value: 'commercial_union_assurance_company_plc', text: 'Commercial Union Assurance Company Plc' },
    { value: 'commercial_union_assurance_group', text: 'Commercial Union Assurance Group' },
    { value: 'confederation_life_insurance_co', text: 'Confederation Life Insurance Co' },
    { value: 'confederation_life_mortgages_services', text: 'Confederation Life Mortgages Services' },
    { value: 'congregational_&amp;_general', text: 'Congregational &amp; General' },
    { value: 'continental_insurance_company_(europe)_limited', text: 'Continental Insurance Company (Europe) Limited' },
    { value: 'coral_underwriting_limited,_gibraltar', text: 'Coral Underwriting Limited, Gibraltar' },
    { value: 'corinthian', text: 'Corinthian' },
    { value: 'corinthian_insurance_company_limited', text: 'Corinthian Insurance Company Limited' },
    { value: 'cork_city_council', text: 'Cork City Council' },
    { value: 'cork_corporation', text: 'Cork Corporation' },
    { value: 'cork_county_council', text: 'Cork County Council' },
    { value: 'cork_north_county_council', text: 'Cork North County Council' },
    { value: 'cornhill_direct', text: 'Cornhill Direct' },
    { value: 'cornhill_insurance_plc', text: 'Cornhill Insurance Plc' },
    { value: 'cornish_mutual_assurance_co_ltd', text: 'Cornish Mutual Assurance Co Ltd' },
    { value: 'counties_home_loan_management', text: 'Counties Home Loan Management' },
    { value: 'coutts_&amp;_co', text: 'Coutts &amp; Co' },
    { value: 'coutts_finance_co', text: 'Coutts Finance Co' },
    { value: 'covea_insurance_plc', text: 'Covea Insurance PLC' },
    { value: 'coventry_building_society', text: 'Coventry Building Society' },
    { value: 'credit_union', text: 'Credit Union' },
    { value: 'credit_union_home_loans', text: 'Credit Union Home Loans' },
    { value: 'crocus_home_loans_ltd', text: 'Crocus Home Loans Ltd' },
    { value: 'crowe', text: 'Crowe' },
    { value: 'crusader_insurance_company_limited', text: 'Crusader Insurance Company Limited' },
    { value: 'cumberland_building_society', text: 'Cumberland Building Society' },
    { value: 'cyprus_popular_bank', text: 'Cyprus Popular Bank' },
    { value: 'darlington_building_society', text: 'Darlington Building Society' },
    { value: 'darlington_mortgage_services_ltd', text: 'Darlington Mortgage Services Ltd' },
    { value: 'das_legal_expenses', text: 'DAS Legal Expenses' },
    { value: 'db_uk_bank_ltd', text: 'DB UK Bank Ltd' },
    { value: 'department_of_agriculture_&amp;_fisheries_&amp;_scotland', text: 'Department Of Agriculture &amp; Fisheries &amp; Scotland' },
    { value: 'derbyshire_building_society', text: 'Derbyshire Building Society' },
    { value: 'derbyshire_home_loans_ltd', text: 'Derbyshire Home Loans Ltd' },
    { value: 'direct_group_limited', text: 'Direct Group Limited' },
    { value: 'direct_line_financial_services_ltd', text: 'Direct Line Financial Services Ltd' },
    { value: 'direct_line_insurance_limited', text: 'Direct Line Insurance Limited' },
    { value: 'distinct_mortgages_ltd', text: 'Distinct Mortgages Ltd' },
    { value: 'dominion_insurance_company_limited', text: 'Dominion Insurance Company Limited' },
    { value: 'donegal_county_council', text: 'Donegal County Council' },
    { value: 'doric', text: 'Doric' },
    { value: 'dowa_insurance_company_(uk)_limited', text: 'Dowa Insurance Company (UK) Limited' },
    { value: 'drake_insurance_plc', text: 'Drake Insurance plc' },
    { value: 'drogheda_borough_council', text: 'Drogheda Borough Council' },
    { value: 'drogheda_corporation', text: 'Drogheda Corporation' },
    { value: 'dual_corporate_risks', text: 'Dual Corporate Risks' },
    { value: 'dublin_city_bank', text: 'Dublin City Bank' },
    { value: 'dublin_city_corporation', text: 'Dublin City Corporation' },
    { value: 'dublin_city_council', text: 'Dublin City Council' },
    { value: 'dublin_corporation', text: 'Dublin Corporation' },
    { value: 'dublin_county_council', text: 'Dublin County Council' },
    { value: 'dublin_south_county_council', text: 'Dublin South County Council' },
    { value: 'dublin/fingal_council', text: 'Dublin/Fingal Council' },
    { value: 'dudley_building_society', text: 'Dudley Building Society' },
    { value: 'dun_laoire_corporation', text: 'Dun Laoire Corporation' },
    { value: 'dun_laoire_county_council', text: 'Dun Laoire County Council' },
    { value: 'dundalk_county_council', text: 'Dundalk County Council' },
    { value: 'dundalk_urban_district_council', text: 'Dundalk Urban District Council' },
    { value: 'dunfermline_building_society', text: 'Dunfermline Building Society' },
    { value: 'dungarvan_urban_district_council', text: 'Dungarvan Urban District Council' },
    { value: 'e-mex_home_funding_ltd', text: 'E-Mex Home Funding Ltd' },
    { value: 'e-sure', text: 'E-Sure' },
    { value: 'e-underwriting', text: 'e-Underwriting' },
    { value: 'eagle_star_(ireland)_ltd', text: 'Eagle Star (Ireland) Ltd' },
    { value: 'eagle_star_direct', text: 'Eagle Star Direct' },
    { value: 'eagle_star_insurance_company_plc', text: 'Eagle Star Insurance Company Plc' },
    { value: 'eagle_star_life_assurance_company_ltd', text: 'Eagle Star Life Assurance Company Ltd' },
    { value: 'earl_shilton_building_society', text: 'Earl Shilton Building Society' },
    { value: 'east_west_insurance_company_limited', text: 'East West Insurance Company Limited' },
    { value: 'eastern_health_board', text: 'Eastern Health Board' },
    { value: 'ebs_building_society', text: 'EBS Building Society' },
    { value: 'ebs_mortgages', text: 'EBS Mortgages' },
    { value: 'ecclesiastical_insurance_office_plc', text: 'Ecclesiastical Insurance Office Plc' },
    { value: 'eclipse', text: 'Eclipse' },
    { value: 'ecology_building_society', text: 'Ecology Building Society' },
    { value: 'economic_insurance_company_limited', text: 'Economic Insurance Company Limited' },
    { value: 'egg_plc', text: 'Egg PLC' },
    { value: 'endeavour_personal_finance_ltd', text: 'Endeavour Personal Finance Ltd' },
    { value: 'endsleigh_insurance_services', text: 'Endsleigh Insurance Services' },
    { value: 'engage_credit_limited', text: 'Engage Credit Limited' },
    { value: 'ennis_urban_district_council', text: 'Ennis Urban District Council' },
    { value: 'ensign', text: 'Ensign' },
    { value: 'enterprise', text: 'Enterprise' },
    { value: 'equitable_life_assurance_society', text: 'Equitable Life Assurance Society' },
    { value: 'equity_bank', text: 'Equity Bank' },
    { value: 'equity_red_star', text: 'Equity Red Star' },
    { value: 'ergo_lebensversicherung_ag', text: 'ERGO Lebensversicherung AG' },
    { value: 'erin', text: 'Erin' },
    { value: 'euclidian_underwriting', text: 'Euclidian Underwriting' },
    { value: 'eurocel_uk_ltd', text: 'Eurocel UK Ltd' },
    { value: 'europa_general_insurance', text: 'Europa General Insurance' },
    { value: 'europa_underwriting_ltd', text: 'Europa Underwriting Ltd' },
    { value: 'european_risk_insurance_(eric)', text: 'European Risk Insurance (ERIC)' },
    { value: 'eversure', text: 'Eversure' },
    { value: 'excess_insurance_company_limited', text: 'Excess Insurance Company Limited' },
    { value: 'fanum_motor_policies', text: 'Fanum Motor Policies' },
    { value: 'fbd_insurance', text: 'FBD Insurance' },
    { value: 'fbo_insurance_company_limited', text: 'FBO Insurance Company Limited' },
    { value: 'federation_general_insurance', text: 'Federation General Insurance' },
    { value: 'fingal_county_council', text: 'Fingal County Council' },
    { value: 'first_active_bank', text: 'First Active Bank' },
    { value: 'first_active_building_society', text: 'First Active Building Society' },
    { value: 'first_active_financial_plc', text: 'First Active Financial plc' },
    { value: 'first_active_mortgages', text: 'First Active Mortgages' },
    { value: 'first_call_direct,_dublin', text: 'First Call Direct, Dublin' },
    { value: 'first_central_insurance', text: 'First Central Insurance' },
    { value: 'first_direct_bank', text: 'First Direct Bank' },
    { value: 'first_mortgage_securities_plc', text: 'First Mortgage Securities Plc' },
    { value: 'first_national_bank', text: 'First National Bank' },
    { value: 'first_national_bank_of_boston', text: 'First National Bank Of Boston' },
    { value: 'first_national_building_society', text: 'First National Building Society' },
    { value: 'first_national_mortgage_company', text: 'First National Mortgage Company' },
    { value: 'first_national_securities_ltd', text: 'First National Securities Ltd' },
    { value: 'first_permanent', text: 'First Permanent' },
    { value: 'first_rate_direct', text: 'First Rate Direct' },
    { value: 'first_trust_bank_ltd', text: 'First Trust Bank Ltd' },
    { value: 'first_trust_building_society', text: 'First Trust Building Society' },
    { value: 'fleet_motor_policies', text: 'Fleet Motor Policies' },
    { value: 'folgate_insurance_company_limited', text: 'Folgate Insurance Company Limited' },
    { value: 'fortis_insurance', text: 'Fortis Insurance' },
    { value: 'fortress_underwriting_agencies_ltd', text: 'Fortress Underwriting Agencies Ltd' },
    { value: 'freedom_funding_limited', text: 'Freedom Funding Limited' },
    { value: 'freedom_lending', text: 'Freedom Lending' },
    { value: 'friends_first', text: 'Friends First' },
    { value: 'friends_provident_life', text: 'Friends Provident Life' },
    { value: 'frizzell_bank_ltd', text: 'Frizzell Bank Ltd' },
    { value: 'frome_selwood_permanent_building_society', text: 'Frome Selwood Permanent Building Society' },
    { value: 'fuji_fire_and_marine_insurance_company_(uk)_limited', text: 'Fuji Fire And Marine Insurance Company (UK) Limited' },
    { value: 'furness_building_society', text: 'Furness Building Society' },
    { value: 'fusion_insurance_services', text: 'Fusion Insurance Services' },
    { value: 'future_mortgages_ltd', text: 'Future Mortgages Ltd' },
    { value: 'g_e_money_home_lending', text: 'G E Money Home Lending' },
    { value: 'ga_bonus', text: 'GA Bonus' },
    { value: 'gainsborough_building_society', text: 'Gainsborough Building Society' },
    { value: 'gallagher_estates_ltd', text: 'Gallagher Estates Ltd' },
    { value: 'galway_city_corporation', text: 'Galway City Corporation' },
    { value: 'galway_city_council', text: 'Galway City Council' },
    { value: 'galway_county_council', text: 'Galway County Council' },
    { value: 'gan_minster_insurance_company_limited', text: 'Gan Minster Insurance Company Limited' },
    { value: 'ge_capital_woodchester', text: 'GE Capital Woodchester' },
    { value: 'ge_life_ltd', text: 'GE Life Ltd' },
    { value: 'gem_mortgages', text: 'GEM Mortgages' },
    { value: 'gemini_funding_ltd', text: 'Gemini Funding Ltd' },
    { value: 'general_accident_1-2-1', text: 'General Accident 1-2-1' },
    { value: 'general_accident_direct', text: 'General Accident Direct' },
    { value: 'general_accident_plc', text: 'General Accident Plc' },
    { value: 'generali_insurance', text: 'Generali Insurance' },
    { value: 'generali_insurance,_dublin', text: 'Generali Insurance, Dublin' },
    { value: 'gmac-rfc_ltd', text: 'GMAC-RFC Ltd' },
    { value: 'godiva_mortgages_limited', text: 'Godiva Mortgages Limited' },
    { value: 'gracechurch_insurance_company_limited', text: 'Gracechurch Insurance Company Limited' },
    { value: 'gresham_life_assurance_society_ltd', text: 'Gresham Life Assurance Society Ltd' },
    { value: 'grindlays_bank_plc', text: 'Grindlays Bank Plc' },
    { value: 'groupama_insurance_company_ltd', text: 'Groupama Insurance Company Ltd' },
    { value: 'guardian', text: 'Guardian' },
    { value: 'guardian_building_society', text: 'Guardian Building Society' },
    { value: 'guardian_direct', text: 'Guardian Direct' },
    { value: 'guardian_eastern_insurance', text: 'Guardian Eastern Insurance' },
    { value: 'guardian_insurance_ireland', text: 'Guardian Insurance Ireland' },
    { value: 'guardian_mortgage_services_ltd', text: 'Guardian Mortgage Services Ltd' },
    { value: 'guardian_royal_exchange', text: 'Guardian Royal Exchange' },
    { value: 'guiness_mahon_mortgage_co_ltd', text: 'Guiness Mahon Mortgage Co Ltd' },
    { value: 'h.f.c._bank_plc', text: 'H.F.C. Bank Plc' },
    { value: 'h.f.c._trust_&amp;_savings', text: 'H.F.C. Trust &amp; Savings' },
    { value: 'habib_bank', text: 'Habib Bank' },
    { value: 'halifax_plc', text: 'Halifax plc' },
    { value: 'hallmark_insurance', text: 'Hallmark Insurance' },
    { value: 'hambro_bank_plc', text: 'Hambro Bank Plc' },
    { value: 'hambro_provident', text: 'Hambro Provident' },
    { value: 'hambro_provident_assurance_ltd', text: 'Hambro Provident Assurance Ltd' },
    { value: 'handelsbanken', text: 'Handelsbanken' },
    { value: 'hanley_economic_building_society', text: 'Hanley Economic Building Society' },
    { value: 'hanover_services', text: 'Hanover Services' },
    { value: 'harpenden_building_society', text: 'Harpenden Building Society' },
    { value: 'hastings_insurance_brokers', text: 'Hastings Insurance Brokers' },
    { value: 'haven_insurance_(gibraltar)', text: 'Haven Insurance (Gibraltar)' },
    { value: 'haven_insurance_policies', text: 'Haven Insurance Policies' },
    { value: 'hbos_plc', text: 'HBOS Plc' },
    { value: 'heath_lambert', text: 'Heath Lambert' },
    { value: 'heritable_bank_ltd', text: 'Heritable Bank Ltd' },
    { value: 'heritable_securities_&amp;_mortgage_investment_assurance_ltd', text: 'Heritable Securities &amp; Mortgage Investment Assurance Ltd' },
    { value: 'heritable_securities_association_ltd', text: 'Heritable Securities Association Ltd' },
    { value: 'hermes', text: 'Hermes' },
    { value: 'hgp_motor_policies', text: 'HGP Motor Policies' },
    { value: 'highway', text: 'Highway' },
    { value: 'hinckley_&amp;_rugby_building_society', text: 'Hinckley &amp; Rugby Building Society' },
    { value: 'hinton_&amp;_wild_(home_plans)_ltd', text: 'Hinton &amp; Wild (Home Plans) Ltd' },
    { value: 'hiscox', text: 'Hiscox' },
    { value: 'holdsure', text: 'Holdsure' },
    { value: 'holmesdale_building_society', text: 'Holmesdale Building Society' },
    { value: 'home_bridging_plc', text: 'Home Bridging Plc' },
    { value: 'home_funding_corporation', text: 'Home Funding Corporation' },
    { value: 'homeloan_management_ltd', text: 'Homeloan Management Ltd' },
    { value: 'household_mortgage_corporation_plc', text: 'Household Mortgage Corporation Plc' },
    { value: 'housing_finance_agencies', text: 'Housing Finance Agencies' },
    { value: 'hsb_haughton_engineering', text: 'HSB Haughton Engineering' },
    { value: 'hsbc', text: 'HSBC' },
    { value: 'i.c.s._motgages', text: 'I.C.S. Motgages' },
    { value: 'i.f.s.c.', text: 'I.F.S.C.' },
    { value: 'i.i.b._bank', text: 'I.I.B. Bank' },
    { value: 'i.i.b._finance', text: 'I.I.B. Finance' },
    { value: 'ibex', text: 'Ibex' },
    { value: 'ibi_homeloans', text: 'IBI Homeloans' },
    { value: 'icc_bank', text: 'ICC Bank' },
    { value: 'icc_corporate_finance', text: 'ICC Corporate Finance' },
    { value: 'icc_investment_bank', text: 'ICC Investment Bank' },
    { value: 'ici,_dublin', text: 'ICI, Dublin' },
    { value: 'ics_building_society', text: 'ICS Building Society' },
    { value: 'ifg', text: 'IFG' },
    { value: 'ifg_building_society', text: 'IFG Building Society' },
    { value: 'ifg_investments', text: 'IFG Investments' },
    { value: 'ifg_mortgages', text: 'IFG Mortgages' },
    { value: 'igroup2_limited,_watford', text: 'IGROUP2 Limited, Watford' },
    { value: 'iib_homeloans_ltd', text: 'IIB Homeloans Ltd' },
    { value: 'ilkeston_permanent_building_society', text: 'Ilkeston Permanent Building Society' },
    { value: 'imb_homeloans', text: 'IMB Homeloans' },
    { value: 'in_retirement_services', text: 'In Retirement Services' },
    { value: 'independent_insurance_company_limited', text: 'Independent Insurance Company Limited' },
    { value: 'industrial_bank_of_scotland_ltd', text: 'Industrial Bank Of Scotland Ltd' },
    { value: 'infinity_mortgages', text: 'Infinity Mortgages' },
    { value: 'ing_direct_n.v.', text: 'ING Direct N.V.' },
    { value: 'insurance_(gb)_limited', text: 'Insurance (GB) Limited' },
    { value: 'insurance_corporation_of_channel_islands', text: 'Insurance Corporation of Channel Islands' },
    { value: 'insurance_corporation_of_ireland', text: 'Insurance Corporation of Ireland' },
    { value: 'integra_insurance_solutions', text: 'Integra Insurance Solutions' },
    { value: 'intelligent_finance', text: 'Intelligent Finance' },
    { value: 'intergalactic_investment_ltd', text: 'Intergalactic Investment Ltd' },
    { value: 'international_insurance_company_of_hannover_limited', text: 'International Insurance Company of Hannover Limited' },
    { value: 'ipswich_building_society', text: 'Ipswich Building Society' },
    { value: 'irani_finance_ltd', text: 'Irani Finance Ltd' },
    { value: 'irish_life_&amp;_pension', text: 'Irish Life &amp; Pension' },
    { value: 'irish_life_and_permanent_plc', text: 'Irish Life and Permanent PLC' },
    { value: 'irish_life_assurance_co_ltd', text: 'Irish Life Assurance Co ltd' },
    { value: 'irish_life_building_society', text: 'Irish Life Building Society' },
    { value: 'irish_life_finance', text: 'Irish Life Finance' },
    { value: 'irish_life_mortgages', text: 'Irish Life Mortgages' },
    { value: 'irish_mutual_building_society', text: 'Irish Mutual Building Society' },
    { value: 'irish_national_insurance', text: 'Irish National Insurance' },
    { value: 'irish_nationwide_building_society', text: 'Irish Nationwide Building Society' },
    { value: 'irish_permanent_plc', text: 'Irish Permanent plc' },
    { value: 'iron_trades_insurance_group', text: 'Iron Trades Insurance Group' },
    { value: 'islamic_bank_of_britain_plc', text: 'Islamic Bank of Britain plc' },
    { value: 'itt_london_&amp;_edinburgh', text: 'ITT London &amp; Edinburgh' },
    { value: 'ius,_galway', text: 'IUS, Galway' },
    { value: 'j_j_gallagher_construction_&amp;_estates_ltd', text: 'J J Gallagher Construction &amp; Estates Ltd' },
    { value: 'j_j_gallagher_construction_ltd', text: 'J J Gallagher Construction Ltd' },
    { value: 'j_j_gallagher_estates_ltd', text: 'J J Gallagher Estates Ltd' },
    { value: 'j_p_morgan_chase_&amp;_co', text: 'J P Morgan Chase &amp; Co' },
    { value: 'jsb', text: 'JSB' },
    { value: 'jubilee', text: 'Jubilee' },
    { value: 'julian_hodge_bank_limited', text: 'Julian Hodge Bank Limited' },
    { value: 'just_retirement', text: 'Just Retirement' },
    { value: 'kbc_homeloans', text: 'KBC Homeloans' },
    { value: 'kensington_mortgage_company', text: 'Kensington Mortgage Company' },
    { value: 'kent_reliance_building_society', text: 'Kent Reliance Building Society' },
    { value: 'kerry_county_council', text: 'Kerry County Council' },
    { value: 'kerry_county_enterprise', text: 'Kerry County Enterprise' },
    { value: 'kestral', text: 'Kestral' },
    { value: 'kgm', text: 'KGM' },
    { value: 'kilcock_and_district_council', text: 'Kilcock And District Council' },
    { value: 'kildare_county_council', text: 'Kildare County Council' },
    { value: 'kilkenny_corporation', text: 'Kilkenny Corporation' },
    { value: 'kilkenny_county_council', text: 'Kilkenny County Council' },
    { value: 'killarney_urban_district_council', text: 'Killarney Urban District Council' },
    { value: 'kinetic_underwriting', text: 'Kinetic Underwriting' },
    { value: 'kleinwort_benson_plc', text: 'Kleinwort Benson Plc' },
    { value: 'koa_insurance_company_(uk)_limited', text: 'Koa Insurance Company (UK) Limited' },
    { value: 'kwik_fit', text: 'Kwik Fit' },
    { value: 'lambeth_building_society', text: 'Lambeth Building Society' },
    { value: 'lancashire_mortgage_corporation', text: 'Lancashire Mortgage Corporation' },
    { value: 'landmark_insurance_company_(uk)_limited', text: 'Landmark Insurance Company (UK) Limited' },
    { value: 'laois_county_council', text: 'Laois County Council' },
    { value: 'laois_urban_district_council', text: 'Laois Urban District Council' },
    { value: 'leadenhall_motor_policies', text: 'Leadenhall Motor Policies' },
    { value: 'leamington_mortgage_corp_plc', text: 'Leamington Mortgage Corp Plc' },
    { value: 'leeds_building_society', text: 'Leeds Building Society' },
    { value: 'leeds_permanent_building_society', text: 'Leeds Permanent Building Society' },
    { value: 'leek_united_building_society', text: 'Leek United Building Society' },
    { value: 'legal_&amp;_general_assurance_society_ltd', text: 'Legal &amp; General Assurance Society Ltd' },
    { value: 'legal_&amp;_general_bank_ltd', text: 'Legal &amp; General Bank Ltd' },
    { value: 'legal_&amp;_general_insurance_limited', text: 'Legal &amp; General Insurance Limited' },
    { value: 'legal_&amp;_general_mortgages_services', text: 'Legal &amp; General Mortgages Services' },
    { value: 'leitrim_county_council', text: 'Leitrim County Council' },
    { value: 'leixlip_county_council', text: 'Leixlip County Council' },
    { value: 'liberty', text: 'Liberty' },
    { value: 'life_&amp;_permanent_plc', text: 'Life &amp; Permanent PLC' },
    { value: 'life_association_of_scotland_investment_funding_ltd', text: 'Life Association Of Scotland Investment Funding Ltd' },
    { value: 'life_association_of_scotland_ltd', text: 'Life Association Of Scotland Ltd' },
    { value: 'limerick_city_corporation', text: 'Limerick City Corporation' },
    { value: 'limerick_city_council', text: 'Limerick City Council' },
    { value: 'limerick_corporation', text: 'Limerick Corporation' },
    { value: 'limerick_county_council', text: 'Limerick County Council' },
    { value: 'link', text: 'Link' },
    { value: 'link_holdings_(gibraltar)_ltd', text: 'Link Holdings (Gibraltar) Ltd' },
    { value: 'lion_insurance_company_limited', text: 'Lion Insurance Company Limited' },
    { value: 'liverpool_victoria', text: 'Liverpool Victoria' },
    { value: 'llanmoor_development_company', text: 'Llanmoor Development Company' },
    { value: 'lloyds_bank_international', text: 'Lloyds Bank International' },
    { value: 'lloyds_bank_plc', text: 'Lloyds Bank Plc' },
    { value: 'lloyds_of_london', text: 'Lloyds of London' },
    { value: 'lloyds_tsb_bank_plc', text: 'Lloyds TSB Bank PLC' },
    { value: 'lloyds_tsb_general_insurance', text: 'Lloyds TSB General Insurance' },
    { value: 'lloyds_tsb_scotland_plc', text: 'Lloyds TSB Scotland Plc' },
    { value: 'lombard_&amp;_ulster_bank', text: 'Lombard &amp; Ulster Bank' },
    { value: 'lombard_&amp;_ulster_banking_ltd', text: 'Lombard &amp; Ulster Banking Ltd' },
    { value: 'lombard_bank_plc', text: 'Lombard Bank Plc' },
    { value: 'lombard_continental_insurance_(uk)_limited', text: 'Lombard Continental Insurance (UK) Limited' },
    { value: 'lombard_north_central_ltd', text: 'Lombard North Central Ltd' },
    { value: 'london_&amp;_manchester_assurance_co_plc', text: 'London &amp; Manchester Assurance Co Plc' },
    { value: 'london_&amp;_manchester_building_society', text: 'London &amp; Manchester Building Society' },
    { value: 'london_&amp;_manchester_mortgages', text: 'London &amp; Manchester Mortgages' },
    { value: 'london_and_lancashire_insurance', text: 'London and Lancashire Insurance' },
    { value: 'london_borough_of_barking_and_dagenham', text: 'London Borough Of Barking And Dagenham' },
    { value: 'london_insurance_group', text: 'London Insurance Group' },
    { value: 'london_mortgage_company', text: 'London Mortgage Company' },
    { value: 'london/scottish_mortgages', text: 'London/Scottish Mortgages' },
    { value: 'longford_county_council', text: 'Longford County Council' },
    { value: 'loughborough_building_society', text: 'Loughborough Building Society' },
    { value: 'louth_county_council', text: 'Louth County Council' },
    { value: 'lovatt_motor_policies', text: 'Lovatt Motor Policies' },
    { value: 'mallow_urban_district_council', text: 'Mallow Urban District Council' },
    { value: 'manchester_building_society', text: 'Manchester Building Society' },
    { value: 'mansfield_building_society', text: 'Mansfield Building Society' },
    { value: 'manufacturers_hanover_trust_co', text: 'Manufacturers Hanover Trust Co' },
    { value: 'marfin_popular_bank_public_company_ltd', text: 'Marfin Popular Bank Public Company Ltd' },
    { value: 'markel_(uk)_ltd', text: 'Markel (UK) Ltd' },
    { value: 'markerstudy_ltd', text: 'Markerstudy Ltd' },
    { value: 'market_harborough_building_society', text: 'Market Harborough Building Society' },
    { value: 'market_harborough_mortgages_ltd', text: 'Market Harborough Mortgages Ltd' },
    { value: 'marks_and_spencer', text: 'Marks and Spencer' },
    { value: 'marlborough_loans_limited', text: 'Marlborough Loans Limited' },
    { value: 'marsden_building_society', text: 'Marsden Building Society' },
    { value: 'mayo_county_council', text: 'Mayo County Council' },
    { value: 'mce_insurance', text: 'MCE Insurance' },
    { value: 'meath_county_council', text: 'Meath County Council' },
    { value: 'melton_mowbray_building_society', text: 'Melton Mowbray Building Society' },
    { value: 'mercantile_building_society', text: 'Mercantile Building Society' },
    { value: 'mercantile_credit_co_ltd', text: 'Mercantile Credit Co Ltd' },
    { value: 'metro_bank_plc', text: 'Metro Bank plc' },
    { value: 'midas_underwriting_agency', text: 'Midas Underwriting Agency' },
    { value: 'midland_and_western', text: 'Midland And Western' },
    { value: 'midland_bank_plc', text: 'Midland Bank Plc' },
    { value: 'midland_bank_trust_co_ltd', text: 'Midland Bank Trust Co Ltd' },
    { value: 'midland_mortgages', text: 'Midland Mortgages' },
    { value: 'midland_mortgages', text: 'Midland Mortgages' },
    { value: 'milestone_motor_policies', text: 'Milestone Motor Policies' },
    { value: 'mitre_insurance_association', text: 'Mitre Insurance Association' },
    { value: 'mitsui_marine', text: 'Mitsui Marine' },
    { value: 'mma_insurance', text: 'MMA Insurance' },
    { value: 'modus_underwriting', text: 'Modus Underwriting' },
    { value: 'monaghan_county_council', text: 'Monaghan County Council' },
    { value: 'monaghan_credit_union', text: 'Monaghan Credit Union' },
    { value: 'monaghan_urban_district_council', text: 'Monaghan Urban District Council' },
    { value: 'money_partners_holdings_limited', text: 'Money Partners Holdings Limited' },
    { value: 'moneypenny_financial', text: 'Moneypenny Financial' },
    { value: 'monmouthshire_building_society', text: 'Monmouthshire Building Society' },
    { value: 'moorhouse', text: 'Moorhouse' },
    { value: 'more_than', text: 'More Than' },
    { value: 'more2life_limited', text: 'More2life Limited' },
    { value: 'morgan_stanley_bank_international_limited', text: 'Morgan Stanley Bank International Limited' },
    { value: 'mortgage_agency_services_no_5', text: 'Mortgage Agency Services No 5' },
    { value: 'mortgage_agency_services_number_4_ltd', text: 'Mortgage Agency Services Number 4 Ltd' },
    { value: 'mortgage_agency_services_plc', text: 'Mortgage Agency Services PLC' },
    { value: 'mortgage_business_plc', text: 'Mortgage Business plc' },
    { value: 'mortgage_corporation_ltd', text: 'Mortgage Corporation Ltd' },
    { value: 'mortgage_direct', text: 'Mortgage Direct' },
    { value: 'mortgage_express_ltd', text: 'Mortgage Express Ltd' },
    { value: 'mortgage_funding_corporation_plc', text: 'Mortgage Funding Corporation Plc' },
    { value: 'mortgage_services_plc', text: 'Mortgage Services Plc' },
    { value: 'mortgage_shop', text: 'Mortgage Shop' },
    { value: 'mortgage_store', text: 'Mortgage Store' },
    { value: 'mortgage_systems_ltd', text: 'Mortgage Systems Ltd' },
    { value: 'mortgage_trust_ltd', text: 'Mortgage Trust Ltd' },
    { value: 'mortgage_works', text: 'Mortgage Works' },
    { value: 'mortgage(s)_1_ltd', text: 'Mortgage(s) 1 Ltd' },
    { value: 'mortgages_plc', text: 'Mortgages plc' },
    { value: 'mt', text: 'MT' },
    { value: 'munich_re', text: 'Munich RE' },
    { value: 'municipal_general_insurance', text: 'Municipal General Insurance' },
    { value: 'municipal_mutual_insurance_limited', text: 'Municipal Mutual Insurance Limited' },
    { value: 'n_e_l_britannia', text: 'N E L Britannia' },
    { value: 'n_e_l_pensions_ltd', text: 'N E L Pensions Ltd' },
    { value: 'n.w.s._bank_plc', text: 'N.W.S. Bank Plc' },
    { value: 'naas_urban_district_council', text: 'Naas Urban District Council' },
    { value: 'nat_employers_mutual_general_insurance_association_limited', text: 'Nat Employers Mutual General Insurance Association Limited' },
    { value: 'nat_west', text: 'Nat West' },
    { value: 'national_&amp;_provincial_building_society', text: 'National &amp; Provincial Building Society' },
    { value: 'national_bank_of_abu_dhabi', text: 'National Bank of Abu Dhabi' },
    { value: 'national_coal_board', text: 'National Coal Board' },
    { value: 'national_counties_building_society', text: 'National Counties Building Society' },
    { value: 'national_employers_life', text: 'National Employers Life' },
    { value: 'national_employers_mutual_general_insurance_association_ltd', text: 'National Employers Mutual General Insurance Association Ltd' },
    { value: 'national_farmers_union_mutual_and_avon_insurance_group', text: 'National Farmers Union Mutual and Avon Insurance Group' },
    { value: 'national_girobank', text: 'National Girobank' },
    { value: 'national_graphical_assocation', text: 'National Graphical Assocation' },
    { value: 'national_home_loans_corporation_plc', text: 'National Home Loans Corporation Plc' },
    { value: 'national_irish_bank', text: 'National Irish Bank' },
    { value: 'national_irish_building_society', text: 'National Irish Building Society' },
    { value: 'national_irish_investments', text: 'National Irish Investments' },
    { value: 'national_irish_mortgage', text: 'National Irish Mortgage' },
    { value: 'national_motor_&amp;_accident', text: 'National Motor &amp; Accident' },
    { value: 'national_mutual_home_loans_plc', text: 'National Mutual Home Loans Plc' },
    { value: 'national_mutual_life_assurance_society', text: 'National Mutual Life Assurance Society' },
    { value: 'national_westminster_home_loans_ltd', text: 'National Westminster Home Loans Ltd' },
    { value: 'nationwide', text: 'Nationwide' },
    { value: 'nationwide_anglia_trust_ltd', text: 'Nationwide Anglia Trust Ltd' },
    { value: 'natwest_mortgage_services', text: 'NatWest Mortgage Services' },
    { value: 'navan_urban_district_council', text: 'Navan Urban District Council' },
    { value: 'nemwill', text: 'Nemwill' },
    { value: 'nenagh_urban_district_council', text: 'Nenagh Urban District Council' },
    { value: 'new_hampshire_insurance', text: 'New Hampshire Insurance' },
    { value: 'new_india_assurance_company_limited', text: 'New India Assurance Company Limited' },
    { value: 'new_ireland_assurance', text: 'New Ireland Assurance' },
    { value: 'new_life_mortgages_ltd', text: 'New Life Mortgages Ltd' },
    { value: 'new_zealand_insurance_plc', text: 'New Zealand Insurance Plc' },
    { value: 'newbury_building_society', text: 'Newbury Building Society' },
    { value: 'newcastle_building_society', text: 'Newcastle Building Society' },
    { value: 'newross_urban_district_council', text: 'Newross Urban District Council' },
    { value: 'niche_capital_ltd', text: 'Niche Capital Ltd' },
    { value: 'nig', text: 'NIG' },
    { value: 'no_previous_insurance', text: 'No Previous Insurance' },
    { value: 'nordern_insurance_company_(uk)_limited', text: 'Nordern Insurance Company (UK) Limited' },
    { value: 'norman_insurance_company_limited', text: 'Norman Insurance Company Limited' },
    { value: 'north_of_england_building_society', text: 'North Of England Building Society' },
    { value: 'north_somerset_council', text: 'North Somerset Council' },
    { value: 'north_wiltshire_building_society', text: 'North Wiltshire Building Society' },
    { value: 'north_yorkshire_mortgages_limited', text: 'North Yorkshire Mortgages Limited' },
    { value: 'north_yorkshire_mortgages_ltd', text: 'North Yorkshire Mortgages Ltd' },
    { value: 'northern_bank', text: 'Northern Bank' },
    { value: 'northern_bank_ltd', text: 'Northern Bank Ltd' },
    { value: 'northern_rock_asset_management_plc_(nram)', text: 'Northern Rock Asset Management Plc (NRAM)' },
    { value: 'northern_rock_plc', text: 'Northern Rock Plc' },
    { value: 'northern_star_insurance_company_limited', text: 'Northern Star Insurance Company Limited' },
    { value: 'norton_finance', text: 'Norton Finance' },
    { value: 'norwich_&amp;_peterborough_(lbs)_ltd', text: 'Norwich &amp; Peterborough (LBS) Ltd' },
    { value: 'norwich_&amp;_peterborough_building_society', text: 'Norwich &amp; Peterborough Building Society' },
    { value: 'norwich_building_society', text: 'Norwich Building Society' },
    { value: 'norwich_irish_building_society', text: 'Norwich Irish Building Society' },
    { value: 'norwich_irish_union', text: 'Norwich Irish Union' },
    { value: 'norwich_union_equity_release', text: 'Norwich Union Equity Release' },
    { value: 'norwich_union_insurance_group', text: 'Norwich Union Insurance Group' },
    { value: 'norwich_union_life_insurance_society_ltd', text: 'Norwich Union Life Insurance Society Ltd' },
    { value: 'norwich_union_mortgage_finance_ltd', text: 'Norwich Union Mortgage Finance Ltd' },
    { value: 'norwich_union_personal_lending_limited', text: 'Norwich Union Personal Lending Limited' },
    { value: 'nottingham_building_society', text: 'Nottingham Building Society' },
    { value: 'nottingham_imperial_building_society', text: 'Nottingham Imperial Building Society' },
    { value: 'oakwood_homeloans_ltd', text: 'Oakwood Homeloans Ltd' },
    { value: 'oakwood_homes_ltd', text: 'Oakwood Homes Ltd' },
    { value: 'ocaso_uk_insurance', text: 'Ocaso UK Insurance' },
    { value: 'octagon_insurance', text: 'Octagon Insurance' },
    { value: 'octavian', text: 'Octavian' },
    { value: 'oddfellows_manchester_unity_friendly_society', text: 'Oddfellows Manchester Unity Friendly Society' },
    { value: 'offaly_county_council', text: 'Offaly County Council' },
    { value: 'offaly_county_enterprise', text: 'Offaly County Enterprise' },
    { value: 'one_account', text: 'One Account' },
    { value: 'one_insurance_(malta)', text: 'One Insurance (Malta)' },
    { value: 'orion_personal_insurances', text: 'Orion Personal Insurances' },
    { value: 'paladin', text: 'Paladin' },
    { value: 'papilio_uk_equity_release_mortgages_ltd', text: 'Papilio UK Equity Release Mortgages Ltd' },
    { value: 'paragon_group_of_companies_plc', text: 'Paragon Group of Companies plc' },
    { value: 'paragon_mortgages_ltd', text: 'Paragon Mortgages Ltd' },
    { value: 'paragon_underwriting', text: 'Paragon Underwriting' },
    { value: 'paramount_insurance_company_limited', text: 'Paramount Insurance Company Limited' },
    { value: 'paratus_amc', text: 'Paratus AMC' },
    { value: 'paribas', text: 'Paribas' },
    { value: 'paribas_lombard', text: 'Paribas Lombard' },
    { value: 'paribas_mortgages', text: 'Paribas Mortgages' },
    { value: 'patnership_home_loans_limited', text: 'Patnership Home Loans Limited' },
    { value: 'pearl_assurance_plc', text: 'Pearl Assurance Plc' },
    { value: 'pegasus', text: 'Pegasus' },
    { value: 'penrith_building_society', text: 'Penrith Building Society' },
    { value: 'permanent_building_society', text: 'Permanent Building Society' },
    { value: 'permanent_t.s.b.', text: 'Permanent T.S.B.' },
    { value: 'permanent_trustee_savings', text: 'Permanent Trustee Savings' },
    { value: 'permanent_tsb_insurance', text: 'Permanent TSB Insurance' },
    { value: 'permanent_tsb_mortgages', text: 'Permanent TSB Mortgages' },
    { value: 'phoenix_assurance', text: 'Phoenix Assurance' },
    { value: 'pioneer_sick_benefit_&amp;_provident_society', text: 'Pioneer Sick Benefit &amp; Provident Society' },
    { value: 'platform_home_loans_limited', text: 'Platform Home Loans Limited' },
    { value: 'plum_underwriting', text: 'Plum Underwriting' },
    { value: 'pohjola_insurance_company_(uk)_limited', text: 'Pohjola Insurance Company (UK) Limited' },
    { value: 'portman_building_society', text: 'Portman Building Society' },
    { value: 'portman_wessex_building_society', text: 'Portman Wessex Building Society' },
    { value: 'post_office', text: 'Post Office' },
    { value: 'precise_mortgages', text: 'Precise Mortgages' },
    { value: 'preferred_assurance', text: 'Preferred Assurance' },
    { value: 'preferred_direct_insurance', text: 'Preferred Direct Insurance' },
    { value: 'preferred_mortgages_ltd', text: 'Preferred Mortgages Ltd' },
    { value: 'premier_direct', text: 'Premier Direct' },
    { value: 'premier_portfolio', text: 'Premier Portfolio' },
    { value: 'prestige_underwriting', text: 'Prestige Underwriting' },
    { value: 'principality_building_society', text: 'Principality Building Society' },
    { value: 'private_label_mortgage_services_ltd', text: 'Private Label Mortgage Services Ltd' },
    { value: 'privilege_insurance', text: 'Privilege Insurance' },
    { value: 'progressive_building_society', text: 'Progressive Building Society' },
    { value: 'property_owners_building_society', text: 'Property Owners Building Society' },
    { value: 'prospero_direct', text: 'Prospero Direct' },
    { value: 'providence_capital_home_loans_ltd', text: 'Providence Capital Home Loans Ltd' },
    { value: 'provident_insurance_plc', text: 'Provident Insurance Plc' },
    { value: 'provident_life_association_ltd', text: 'Provident Life Association Ltd' },
    { value: 'provident_mutual_life_assurance_association', text: 'Provident Mutual Life Assurance Association' },
    { value: 'provincial_assurance_co_ltd', text: 'Provincial Assurance Co Ltd' },
    { value: 'provincial_insurance_plc', text: 'Provincial Insurance Plc' },
    { value: 'prudential_assurance_company_ltd', text: 'Prudential Assurance Company Ltd' },
    { value: 'prudential_banking_plc', text: 'Prudential Banking plc' },
    { value: 'prudential_lifetime_mortgages', text: 'Prudential Lifetime Mortgages' },
    { value: 'qbe_international_insurance_limited', text: 'QBE International Insurance Limited' },
    { value: 'quinn_direct', text: 'Quinn Direct' },
    { value: 'rac', text: 'RAC' },
    { value: 'randall_&amp;_quilter_ltd', text: 'Randall &amp; Quilter Ltd' },
    { value: 'rathdown_county_council', text: 'Rathdown County Council' },
    { value: 'rb', text: 'RB' },
    { value: 'rea_mortgage_choice', text: 'Rea Mortgage Choice' },
    { value: 'redstar_policies', text: 'Redstar Policies' },
    { value: 'redstone_mortgages', text: 'Redstone Mortgages' },
    { value: 'redstone_mortgages_plc', text: 'Redstone Mortgages PLC' },
    { value: 'refuge_assurance_plc', text: 'Refuge Assurance Plc' },
    { value: 'regency', text: 'Regency' },
    { value: 'regency_motor_policies', text: 'Regency Motor Policies' },
    { value: 'regency_west_of_england_building_society', text: 'Regency West Of England Building Society' },
    { value: 'reliance_fire_and_accident_insurance_corporation_limited', text: 'Reliance Fire And Accident Insurance Corporation Limited' },
    { value: 'renown', text: 'Renown' },
    { value: 'rentguard_ltd', text: 'Rentguard Ltd' },
    { value: 'rfc_mortgage_services_ltd', text: 'RFC Mortgage Services Ltd' },
    { value: 'rooftop_mortgages_limited', text: 'Rooftop Mortgages Limited' },
    { value: 'roscommon_county_council', text: 'Roscommon County Council' },
    { value: 'royal_&amp;_sun_alliance_(ireland)', text: 'Royal &amp; Sun Alliance (Ireland)' },
    { value: 'royal_ancient_order_of_buffaloes', text: 'Royal Ancient Order Of Buffaloes' },
    { value: 'royal_bank_of_canada', text: 'Royal Bank Of Canada' },
    { value: 'royal_bank_of_scotland_plc', text: 'Royal Bank Of Scotland Plc' },
    { value: 'royal_insurance_(uk)_limited', text: 'Royal Insurance (UK) Limited' },
    { value: 'royal_insurance_co_ltd', text: 'Royal Insurance Co Ltd' },
    { value: 'royal_life_assurance', text: 'Royal Life Assurance' },
    { value: 'royal_london_general_insurance_company_limited', text: 'Royal London General Insurance Company Limited' },
    { value: 'royal_london_homebuy_ltd', text: 'Royal London Homebuy Ltd' },
    { value: 'royal_london_mutual_assurance_society_ltd', text: 'Royal London Mutual Assurance Society Ltd' },
    { value: 'royal_trust_co_of_canada', text: 'Royal Trust Co Of Canada' },
    { value: 'rsa', text: 'RSA' },
    { value: 'sabre_insurance_company_limited', text: 'Sabre Insurance Company Limited' },
    { value: 'saffron_walden_herts_&amp;_essex_building_society', text: 'Saffron Walden Herts &amp; Essex Building Society' },
    { value: 'saga_insurance', text: 'Saga Insurance' },
    { value: 'sainsburys_bank', text: 'Sainsburys Bank' },
    { value: 'sampo_insurance_co_(uk)_ltd', text: 'Sampo Insurance Co (UK) Ltd' },
    { value: 'samsung_insurance_company_of_europe_limited', text: 'Samsung Insurance Company of Europe Limited' },
    { value: 'santander', text: 'Santander' },
    { value: 'scandinavian_bank_group_plc', text: 'Scandinavian Bank Group Plc' },
    { value: 'scarborough_building_society', text: 'Scarborough Building Society' },
    { value: 'scotlife_home_loans', text: 'Scotlife Home Loans' },
    { value: 'scottish_amicable_life_assurance_society', text: 'Scottish Amicable Life Assurance Society' },
    { value: 'scottish_building_society', text: 'Scottish Building Society' },
    { value: 'scottish_equitable_life_assurance_society', text: 'Scottish Equitable Life Assurance Society' },
    { value: 'scottish_general_insurance_company_limited', text: 'Scottish General Insurance Company Limited' },
    { value: 'scottish_legal_life_assurance_society', text: 'Scottish Legal Life Assurance Society' },
    { value: 'scottish_life_assurance_co', text: 'Scottish Life Assurance Co' },
    { value: 'scottish_mutual_assurance_society', text: 'Scottish Mutual Assurance Society' },
    { value: 'scottish_providence', text: 'Scottish Providence' },
    { value: 'scottish_provident_institution', text: 'Scottish Provident Institution' },
    { value: 'scottish_provident_mutual_life_association', text: 'Scottish Provident Mutual Life Association' },
    { value: 'scottish_widows_bank_plc', text: 'Scottish Widows Bank plc' },
    { value: 'scottish_widows_fund_&amp;_life_assurance_society', text: 'Scottish Widows Fund &amp; Life Assurance Society' },
    { value: 'secretan', text: 'Secretan' },
    { value: 'security_pacific_trust', text: 'Security Pacific Trust' },
    { value: 'sentry', text: 'Sentry' },
    { value: 'service', text: 'Service' },
    { value: 'sg_kleinwort_hambros_bank_(ci)_ltd', text: 'SG Kleinwort Hambros Bank (CI) Ltd' },
    { value: 'shanghai_commercial_bank_ltd', text: 'Shanghai Commercial Bank Ltd' },
    { value: 'shannon_development', text: 'Shannon Development' },
    { value: 'shared_home_investments', text: 'Shared Home Investments' },
    { value: 'shawbrook_mortgages', text: 'Shawbrook Mortgages' },
    { value: 'shead', text: 'Shead' },
    { value: 'shepshed_building_society', text: 'Shepshed Building Society' },
    { value: 'shield_insurance_company_limited', text: 'Shield Insurance Company Limited' },
    { value: 'skandia_life', text: 'Skandia Life' },
    { value: 'skandia_trust', text: 'Skandia Trust' },
    { value: 'skipton_building_society', text: 'Skipton Building Society' },
    { value: 'skipton_international_ltd', text: 'Skipton International Ltd' },
    { value: 'sligo_borough_council', text: 'Sligo Borough Council' },
    { value: 'sligo_corporation', text: 'Sligo Corporation' },
    { value: 'sligo_county_council', text: 'Sligo County Council' },
    { value: 'smt_insurance_company_limited', text: 'SMT Insurance Company Limited' },
    { value: 'smurfit_finance_ltd', text: 'Smurfit Finance Ltd' },
    { value: 'societe_generale', text: 'Societe Generale' },
    { value: 'solar', text: 'Solar' },
    { value: 'sons_of_scotland_temperance_friendly_society', text: 'Sons Of Scotland Temperance Friendly Society' },
    { value: 'southern_pacific_mortgages_ltd', text: 'Southern Pacific Mortgages Ltd' },
    { value: 'sphere', text: 'Sphere' },
    { value: 'sportscover', text: 'Sportscover' },
    { value: 'st_katherines_policies', text: 'St Katherines Policies' },
    { value: 'st_stephens_motor_policies', text: 'St Stephens Motor Policies' },
    { value: 'stafford_railway_building_society', text: 'Stafford Railway Building Society' },
    { value: 'staffordshire_building_society', text: 'Staffordshire Building Society' },
    { value: 'standard_bank', text: 'Standard Bank' },
    { value: 'standard_building_society', text: 'Standard Building Society' },
    { value: 'standard_chartered_bank_ltd', text: 'Standard Chartered Bank Ltd' },
    { value: 'standard_chartered_bank_plc', text: 'Standard Chartered Bank Plc' },
    { value: 'standard_life_assurance_co', text: 'Standard Life Assurance Co' },
    { value: 'standard_life_bank_limited', text: 'Standard Life Bank Limited' },
    { value: 'standard_property_investment_co_ltd', text: 'Standard Property Investment Co Ltd' },
    { value: 'standard_trust_ltd', text: 'Standard Trust Ltd' },
    { value: 'start_mortgages_ltd', text: 'Start Mortgages Ltd' },
    { value: 'sterling', text: 'Sterling' },
    { value: 'stonehaven_uk_limited', text: 'Stonehaven UK Limited' },
    { value: 'stroud_&amp;_swindon_building_society', text: 'Stroud &amp; Swindon Building Society' },
    { value: 'sumitomo_bank_ltd', text: 'Sumitomo Bank Ltd' },
    { value: 'summit', text: 'Summit' },
    { value: 'sun_alliance', text: 'Sun Alliance' },
    { value: 'sun_alliance_insurance_uk', text: 'Sun Alliance Insurance UK' },
    { value: 'sun_bank_plc', text: 'Sun Bank plc' },
    { value: 'sun_life_assurance_society_ltd', text: 'Sun Life Assurance Society Ltd' },
    { value: 'sunderland_&amp;_south_shields_building_society', text: 'Sunderland &amp; South Shields Building Society' },
    { value: 'swan', text: 'Swan' },
    { value: 'swansea_building_society', text: 'Swansea Building Society' },
    { value: 'swift_1st', text: 'Swift 1st' },
    { value: 'swift_advances_plc', text: 'Swift Advances plc' },
    { value: 'swinton', text: 'Swinton' },
    { value: 'swiss_bank_corporation', text: 'Swiss Bank Corporation' },
    { value: 'symphony_insurance', text: 'Symphony Insurance' },
    { value: 't.s.b._scotland_plc', text: 'T.S.B. Scotland Plc' },
    { value: 'tanker_insurance', text: 'Tanker Insurance' },
    { value: 'target_home_loans', text: 'Target Home Loans' },
    { value: 'target_life_assurance_co_ltd', text: 'Target Life Assurance Co Ltd' },
    { value: 'teachers_building_society', text: 'Teachers Building Society' },
    { value: 'terra_nova_insurance_co_ltd', text: 'Terra Nova Insurance Co Ltd' },
    { value: 'tesco_bank', text: 'Tesco Bank' },
    { value: 'tesco_insurance', text: 'Tesco Insurance' },
    { value: 'thames_mortgages', text: 'Thames Mortgages' },
    { value: 'the_borough_council', text: 'The Borough Council' },
    { value: 'the_continental_insurance_co._(uk)_ltd', text: 'The Continental Insurance Co. (UK) Ltd' },
    { value: 'the_insurance_service', text: 'The Insurance Service' },
    { value: 'the_mortgage_centre', text: 'The Mortgage Centre' },
    { value: 'the_mortgage_lender_ltd', text: 'The Mortgage Lender Ltd' },
    { value: 'the_mortgage_works_(uk)_plc', text: 'The Mortgage Works (UK) plc' },
    { value: 'the_national_bank_of_ireland', text: 'The National Bank Of Ireland' },
    { value: 'the_warwick_insurance_co_ltd', text: 'The Warwick Insurance Co Ltd' },
    { value: 'thurles_urban_district_council', text: 'Thurles Urban District Council' },
    { value: 'tipperary_north_county_council', text: 'Tipperary North County Council' },
    { value: 'tipperary_south_county_council', text: 'Tipperary South County Council' },
    { value: 'tipperary_urban_district_council', text: 'Tipperary Urban District Council' },
    { value: 'tipton_&amp;_coseley_building_society', text: 'Tipton &amp; Coseley Building Society' },
    { value: 'tiuta_plc', text: 'Tiuta PLC' },
    { value: 'topaz_finance_plc', text: 'Topaz Finance PLC' },
    { value: 'torch', text: 'Torch' },
    { value: 'touchline_insurance_company_limited', text: 'Touchline Insurance Company Limited' },
    { value: 'towergate_insurance', text: 'Towergate Insurance' },
    { value: 'tradewise_insurance_services_ltd', text: 'Tradewise Insurance Services Ltd' },
    { value: 'trafalgar_insurance', text: 'Trafalgar Insurance' },
    { value: 'tralee_urban_district_council', text: 'Tralee Urban District Council' },
    { value: 'travelers_insurance_company_ltd', text: 'Travelers Insurance Company Ltd' },
    { value: 'trim_urban_district_council', text: 'Trim Urban District Council' },
    { value: 'trinity_insurance_company_limited', text: 'Trinity Insurance Company Limited' },
    { value: 'trojan_motor_policies', text: 'Trojan Motor Policies' },
    { value: 'trustee_savings_bank_plc', text: 'Trustee Savings Bank Plc' },
    { value: 'tullamore_county_council', text: 'Tullamore County Council' },
    { value: 'turegum_insurance_co', text: 'Turegum Insurance Co' },
    { value: 'tusa_bank', text: 'Tusa Bank' },
    { value: 'tyne_assurance_society', text: 'Tyne Assurance Society' },
    { value: 'uap_provincial', text: 'UAP Provincial' },
    { value: 'ucb_home_loans', text: 'UCB Home Loans' },
    { value: 'uk_civil_service_building_society', text: 'UK Civil Service Building Society' },
    { value: 'uk_general', text: 'UK General' },
    { value: 'uk_provident_institution', text: 'UK Provident Institution' },
    { value: 'ulster_bank', text: 'Ulster Bank' },
    { value: 'ulster_bank_business', text: 'Ulster Bank Business' },
    { value: 'ulster_bank_mortgages', text: 'Ulster Bank Mortgages' },
    { value: 'ulster_bank_of_ireland', text: 'Ulster Bank Of Ireland' },
    { value: 'union_bank_of_switzerland', text: 'Union Bank Of Switzerland' },
    { value: 'united_bank_of_kuwait_plc', text: 'United Bank Of Kuwait plc' },
    { value: 'united_commercial_bank_home_loans', text: 'United Commercial Bank Home Loans' },
    { value: 'united_dominions_trust_ltd', text: 'United Dominions Trust Ltd' },
    { value: 'united_friendly_insurance_co_ltd', text: 'United Friendly Insurance Co Ltd' },
    { value: 'united_kingdom_civil_service_benefit_society', text: 'United Kingdom Civil Service Benefit Society' },
    { value: 'united_overseas_bank_ltd', text: 'United Overseas Bank Ltd' },
    { value: 'united_trust_bank', text: 'United Trust Bank' },
    { value: 'unity_homeloans', text: 'Unity Homeloans' },
    { value: 'universal_building_society', text: 'Universal Building Society' },
    { value: 'unknown', text: 'Unknown' },
    { value: 'unlisted_insurer', text: 'Unlisted Insurer' },
    { value: 'usaa_limited', text: 'USAA Limited' },
    { value: 'vasek', text: 'Vasek' },
    { value: 'vernon_building_society', text: 'Vernon Building Society' },
    { value: 'verso', text: 'Verso' },
    { value: 'virgin_money', text: 'Virgin money' },
    { value: 'vision_underwriting_ltd', text: 'Vision Underwriting Ltd' },
    { value: 'warwick_motor_policies', text: 'Warwick Motor Policies' },
    { value: 'waterford_city_council', text: 'Waterford City Council' },
    { value: 'waterford_corporation', text: 'Waterford Corporation' },
    { value: 'waterford_county_council', text: 'Waterford County Council' },
    { value: 'waterford_county_enterprise', text: 'Waterford County Enterprise' },
    { value: 'waterford_credit_union', text: 'Waterford Credit Union' },
    { value: 'wave_lending_ltd', text: 'Wave Lending Ltd' },
    { value: 'webb_resolutions_ltd', text: 'Webb Resolutions Ltd' },
    { value: 'wellington_insurance_service', text: 'Wellington Insurance Service' },
    { value: 'wesleyan_&amp;_general_assurance_society', text: 'Wesleyan &amp; General Assurance Society' },
    { value: 'wesleyan_assurance_society', text: 'Wesleyan Assurance Society' },
    { value: 'wesleyan_home_loans_ltd', text: 'Wesleyan Home Loans Ltd' },
    { value: 'wessex', text: 'Wessex' },
    { value: 'west_bromwich_building_society', text: 'West Bromwich Building Society' },
    { value: 'west_bromwich_mortgage_company_ltd', text: 'West Bromwich Mortgage Company Ltd' },
    { value: 'west_yorkshire_insurance_company', text: 'West Yorkshire Insurance Company' },
    { value: 'western_australia', text: 'Western Australia' },
    { value: 'western_rural_development', text: 'Western Rural Development' },
    { value: 'western_trust_&amp;_savings_ltd', text: 'Western Trust &amp; Savings Ltd' },
    { value: 'westmeath_county_council', text: 'Westmeath County Council' },
    { value: 'westminster_motor_insurance_association', text: 'Westminster Motor Insurance Association' },
    { value: 'westpac_banking_corporation', text: 'Westpac Banking Corporation' },
    { value: 'westport_urban_district_council', text: 'Westport Urban District Council' },
    { value: 'wexford_borough_council', text: 'Wexford Borough Council' },
    { value: 'wexford_corporation', text: 'Wexford Corporation' },
    { value: 'wexford_county_council', text: 'Wexford County Council' },
    { value: 'wexford_credit_union', text: 'Wexford Credit Union' },
    { value: 'wicklow_county_council', text: 'Wicklow County Council' },
    { value: 'wicklow_urban_district_council', text: 'Wicklow Urban District Council' },
    { value: 'williams_&amp;_glyns_bank_plc', text: 'Williams &amp; Glyns Bank Plc' },
    { value: 'windsor_life_assurance_co_ltd', text: 'Windsor Life Assurance Co Ltd' },
    { value: 'winterthur_life', text: 'Winterthur Life' },
    { value: 'woolwich_plc', text: 'Woolwich plc' },
    { value: 'wren', text: 'Wren' },
    { value: 'wrightway_underwriting_limited', text: 'Wrightway Underwriting Limited' },
    { value: 'yes_insurance', text: 'Yes Insurance' },
    { value: 'yorkshire_bank', text: 'Yorkshire Bank' },
    { value: 'yorkshire_bank_trust_co_ltd', text: 'Yorkshire Bank Trust Co Ltd' },
    { value: 'yorkshire_building_society', text: 'Yorkshire Building Society' },
    { value: 'yorkshire_general_life_assurance_co_ltd', text: 'Yorkshire General Life Assurance Co Ltd' },
    { value: 'yorkshire_insurance', text: 'Yorkshire Insurance' },
    { value: 'youghal_urban_district_council', text: 'Youghal Urban District Council' },
    { value: 'zenith', text: 'Zenith' },
    { value: 'zurich_insurance_plc', text: 'Zurich Insurance plc' },
    { value: 'zurich_municipal', text: 'Zurich Municipal' },
    { value: 'zz_-_not_covered_by_any_other_item_on_the_list', text: 'ZZ - Not Covered By Any Other Item On The List' }
  ]
};

$(document).ready(function () {
  var $select = $('#insurer_name_list');
  $.each(groupedInsOptions['insurer_name_options'], function(_, option) {
    $select.append($('<option>', { value: option.text, text: option.text }));
  });
  
});
